# Fetching the minified node image on apline linux
FROM node:20.14.0-alpine

# Declaring env
ENV PORT 3000
ENV USER_NAME "user0"
ENV USER_PASSWORD "MO3izU4EmfXhj8PB"
ENV CLUSTER "@cluster0.8cc9pmg.mongodb.net/CarbonCredit?retryWrites=true&w=majority&appName=Cluster0"

# Setting up the work directory
WORKDIR /

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install
RUN npm run build

# Starting our application
CMD [ "npm" ,"start"]

# Exposing server port
EXPOSE 3000 